server.port: 8081

slack:
  token: token
  channel:
    monitor: '#schedule-bot'

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  datasource:
    url: jdbc:mysql://34.70.124.200:3306/schedule?useSSL=false
    username: root
    password: password